<?php

	if(!isset($_POST['polEffDate'])){
		echo "Please input: polEffDate";
	}
	else{
		echo "Success!!!";
	}

	$polMasPolNum="";
	$polQuoNum=$_SESSION["polQuoNum"];
	$polNum="";
	$polCat="N/A";
	$polReFlag="N/A";
	$polStatusIDFK="1";
	$polEffDate=trim($_POST['polEffDate']);
	$polExpDate=trim($_POST['polExpDate']);
	$polQuoCreateDate=$_SESSION["startSessionDateTime"];
	$polQuoDate=date("Y-m-d H:i:s");
	$polProDate="0000-00-00 00:00:00";
	$polAppReceivedDate="0000-00-00 00:00:00";
	$polIssueDate="0000-00-00 00:00:00";
	$polIssueBy="";
	$polPRODIDFK="1";
	$polPREMIDFK=trim($_POST['polPREMIDFK']);
	$polCUSIDFKPHD=trim($_POST['polCUSIDFKPHD']);
	$polCUSAddrIDPHD=trim($_POST['polCUSAddrIDPHD']);
	$polCUSIDFKINS=trim($_POST['polCUSIDFKINS']);
	$polCUSAddrIDINS=trim($_POST['polCUSAddrIDINS']);
	$polVEHIDFK=trim($_POST['polVEHIDFK']);
	$polUpdatedDate=date("Y-m-d H:i:s");
	$polUpdatedBy=$_SESSION["usrName"];
	$vehIDPK=trim($_POST['vehIDPK']);
	$vehTARIDFK=trim($_POST['tarIDPK']);
	$vehTARVehCodeFK=trim($_POST['tarVehCodePK']);
	$vehREDKEYFK=trim($_POST['redKey']);
	$vehLicenseNum=trim($_POST['vehLicenseNum']);
	$vehChassisNum=trim($_POST['vehChassisNum']);
	$vehCapacity=trim($_POST['vehCapacity']);
	$vehSeat=trim($_POST['vehSeat']);
	$vehWeight=trim($_POST['vehWeight']);
	$vehEngineNum="N/A";
	$vehNewCar="N/A";
	$vehDriveArea="N/A";
	$vehProvIDFK="-1";
	$vehColor="N/A";
	$vehCountry="N/A";
	$vehQuoNumRef=$_SESSION["polQuoNum"];
	$vehUpdatedDate=date("Y-m-d H:i:s");
	$vehUpdatedBy=$_SESSION["usrName"];
	$perIDPK=trim($_POST['perIDPK']);
	$perSalu=trim($_POST['perSalu']);
	$perFName=trim($_POST['perFName']);
	$perMName="N/A";
	$perLName=trim($_POST['perLName']);
	$perDOB=date("Y-m-d",strtotime($_POST['perDOB']));
	$perCardType=trim($_POST['perCardType']);
	$perCardNo=trim($_POST['perCardNo']);
	$perExpDate=date("Y-m-d",strtotime($_POST['perExpDate']));
	$perUpdatedDate=date("Y-m-d H:i:s");
	$perUpdatedBy=$_SESSION["usrName"];
	$addrIDPK=trim($_POST['addrIDPK']);
	$addrLine1=trim($_POST['addrLine1']);
	$addrLine2=trim($_POST['addrLine2']);
	$addrSubDist=trim($_POST['addrSubDist']);
	$addrDist=trim($_POST['addrDist']);
	$addrProv=trim($_POST['addrProv']);
	$addrZipCode=trim($_POST['addrZipCode']);
	$addrGeo="N/A";
	$addrEmail=trim($_POST['addrEmail']);
	$addrContType1=trim($_POST['addrContType1']);
	$addrContNum1=trim($_POST['addrContNum1']);
	$addrContType2="-1";
	$addrContNum2="N/A";
	$addrUpdatedDate=date("Y-m-d H:i:s");
	$addrUpdatedBy=$_SESSION["usrName"];
	$tarIDPK=trim($_POST['tarIDPK']);
	$tarVehCodePK=trim($_POST['tarVehCodePK']);
	$redKey=trim($_POST['redKey']);
	$redMake=trim($_POST['redMake']);
	$redModel=trim($_POST['redModel']);
	$redYear=trim($_POST['redYear']);
	$redDesc=trim($_POST['redDesc']);
	$premStdNet=trim($_POST['premStdNet']);
	$premStdVat=trim($_POST['premStdVat']);
	$premStdStampDuty=trim($_POST['premStdStampDuty']);
	$premStdTotal=trim($_POST['premStdTotal']);
	$premPercentVat=7;
	$premPerDiscount="0";
	$premDiscountFlag="N";
	$premDiscount="0";
	$premNet=trim($_POST['premNet']);
	$premStampDuty=trim($_POST['premStampDuty']);
	$premVat=trim($_POST['premVat']);
	$premTotal=trim($_POST['premTotal']);
	$premQuoNumRef=$_SESSION["polQuoNum"];
	$premUpdatedDate=date("Y-m-d H:i:s");
	$premUpdatedBy=$_SESSION["usrName"];

	echo "polMasPolNum:".$polMasPolNum."<br>";
	echo "polQuoNum:".$polQuoNum."<br>";
	echo "polNum:".$polNum."<br>";
	echo "polCat:".$polCat."<br>";
	echo "polReFlag:".$polReFlag."<br>";
	echo "polStatusIDFK:".$polStatusIDFK."<br>";
	echo "polEffDate:".$polEffDate."<br>";
	echo "polEffDate:".$polEffDate."<br>";
	echo "polQuoCreateDate:".$polQuoCreateDate."<br>";
	echo "polQuoDate:".$polQuoDate."<br>";
	echo "polProDate:".$polProDate."<br>";
	echo "polAppReceivedDate:".$polAppReceivedDate."<br>";
	echo "polIssueDate:".$polIssueDate."<br>";
	echo "polIssueBy:".$polIssueBy."<br>";
	echo "polPRODIDFK:".$polPRODIDFK."<br>";
	echo "polPREMIDFK:".$polPREMIDFK."<br>";
	echo "polCUSIDFKPHD:".$polCUSIDFKPHD."<br>";
	echo "polCUSAddrIDPHD:".$polCUSAddrIDPHD."<br>";
	echo "polCUSIDFKINS:".$polCUSIDFKINS."<br>";
	echo "polCUSAddrIDINS:".$polCUSAddrIDINS."<br>";
	echo "polVEHIDFK:".$polVEHIDFK."<br>";
	echo "polUpdatedDate:".$polUpdatedDate."<br>";
	echo "polUpdatedBy:".$polUpdatedBy."<br>";
	echo "vehIDPK:".$vehIDPK."<br>";
	echo "vehTARVehCodeFK:".$vehTARVehCodeFK."<br>";
	echo "vehREDKEYFK:".$vehREDKEYFK."<br>";
	echo "vehLicenseNum:".$vehLicenseNum."<br>";
	echo "vehChassisNum:".$vehChassisNum."<br>";
	echo "vehCapacity:".$vehCapacity."<br>";
	echo "vehSeat:".$vehSeat."<br>";
	echo "vehWeight:".$vehWeight."<br>";
	echo "vehEngineNum:".$vehEngineNum."<br>";
	echo "vehNewCar:".$vehNewCar."<br>";
	echo "vehDriveArea:".$vehDriveArea."<br>";
	echo "vehProvIDFK:".$vehProvIDFK."<br>";
	echo "vehColor:".$vehColor."<br>";
	echo "vehCountry:".$vehCountry."<br>";
	echo "vehQuoNumRef:".$vehQuoNumRef."<br>";
	echo "vehUpdatedDate:".$vehUpdatedDate."<br>";
	echo "vehUpdatedBy:".$vehUpdatedBy."<br>";
	echo "perIDPK:".$perIDPK."<br>";
	echo "perSalu:".$perSalu."<br>";
	echo "perFName:".$perFName."<br>";
	echo "perMName:".$perMName."<br>";
	echo "perLName:".$perLName."<br>";
	echo "perDOB:".$perDOB."<br>";
	echo "perCardType:".$perCardType."<br>";
	echo "perCardNo:".$perCardNo."<br>";
	echo "perExpDate:".$perExpDate."<br>";
	echo "perUpdatedDate:".$perUpdatedDate."<br>";
	echo "perUpdatedBy:".$perUpdatedBy."<br>";
	echo "addrIDPK:".$addrIDPK."<br>";
	echo "addrLine1:".$addrLine1."<br>";
	echo "addrLine2:".$addrLine2."<br>";
	echo "addrSubDist:".$addrSubDist."<br>";
	echo "addrDist:".$addrDist."<br>";
	echo "addrProv:".$addrProv."<br>";
	echo "addrZipCode:".$addrZipCode."<br>";
	echo "addrGeo:".$addrGeo."<br>";
	echo "addrEmail:".$addrEmail."<br>";
	echo "addrContType1:".$addrContType1."<br>";
	echo "addrContNum1:".$addrContNum1."<br>";
	echo "addrContType2:".$addrContType2."<br>";
	echo "addrContNum2:".$addrContNum2."<br>";
	echo "addrUpdatedDate:".$addrUpdatedDate."<br>";
	echo "addrUpdatedBy:".$addrUpdatedBy."<br>";
	echo "remove-tarVehCodePK:".$tarVehCodePK."<br>";
	// echo "tarBody:".$tarBody."<br>";
	// echo "tarSubBody:".$tarSubBody."<br>";
	echo "remove-redKey:".$redKey."<br>";
	echo "remove-redMake:".$redMake."<br>";
	echo "remove-redModel:".$redModel."<br>";
	echo "remove-redYear:".$redYear."<br>";
	echo "remove-redDesc:".$redDesc."<br>";
	echo "premStdNet:".$premStdNet."<br>";
	echo "premStdVat:".$premStdVat."<br>";
	echo "premStdStampDuty:".$premStdStampDuty."<br>";
	echo "premStdTotal:".$premStdTotal."<br>";
	echo "premPercentVat:".$premPercentVat."<br>";
	echo "premPerDiscount:".$premPerDiscount."<br>";
	echo "premDiscountFlag:".$premDiscountFlag."<br>";
	echo "premDiscount:".$premDiscount."<br>";
	echo "premNet:".$premNet."<br>";
	echo "premStampDuty:".$premStampDuty."<br>";
	echo "premVat:".$premVat."<br>";
	echo "premTotal:".$premTotal."<br>";
	echo "premQuoNumRef:".$premQuoNumRef."<br>";
	echo "premUpdatedDate:".$premUpdatedDate."<br>";
	echo "premUpdatedBy:".$premUpdatedBy."<br>";



?>